// Automatically generated by declarative-routing, do NOT edit
import { z } from 'zod'

import * as ProtectedNadzornaPloscaAktualniProjektSlugRoute from '@/app/(protected)/nadzorna-plosca/aktualni-projekt/[slug]/page.info'
import * as ProtectedNadzornaPloscaAktualniProjektNovRoute from '@/app/(protected)/nadzorna-plosca/aktualni-projekt/nov/page.info'
import * as ProtectedNadzornaPloscaRoute from '@/app/(protected)/nadzorna-plosca/page.info'
import * as PublicRoute from '@/app/(public)/page.info'
import * as PublicProjektSlugIdRoute from '@/app/(public)/projekt/[slug]/[id]/page.info'
import * as PublicProjektSlugRoute from '@/app/(public)/projekt/[slug]/page.info'
import * as PublicProjektiRoute from '@/app/(public)/projekti/page.info'
import * as ApiAuthNextauthRoute from '@/app/api/auth/[...nextauth]/route.info'
import * as ApiUploadthingRoute from '@/app/api/uploadthing/route.info'
import * as AuthErrorRoute from '@/app/auth/error/page.info'
import * as AuthLoginRoute from '@/app/auth/login/page.info'
import * as AuthNewPasswordRoute from '@/app/auth/new-password/page.info'
import * as AuthNewVerificationRoute from '@/app/auth/new-verification/page.info'
import * as AuthRegisterRoute from '@/app/auth/register/page.info'
import * as AuthResetPasswordRoute from '@/app/auth/reset-password/page.info'

import { makeRoute } from './makeRoute'

const defaultInfo = {
  search: z.object({
  }),
}

export const ProtectedNadzornaPlosca = makeRoute(
  '/(protected)/nadzorna-plosca',
  {
    ...defaultInfo,
    ...ProtectedNadzornaPloscaRoute.Route,
  },
)

export const ProtectedNadzornaPloscaAktualniProjektSlug = makeRoute(
  '/(protected)/nadzorna-plosca/aktualni-projekt/[slug]',
  {
    ...defaultInfo,
    ...ProtectedNadzornaPloscaAktualniProjektSlugRoute.Route,
  },
)

export const ProtectedNadzornaPloscaAktualniProjektNov = makeRoute(
  '/(protected)/nadzorna-plosca/aktualni-projekt/nov',
  {
    ...defaultInfo,
    ...ProtectedNadzornaPloscaAktualniProjektNovRoute.Route,
  },
)

export const Public = makeRoute(
  '/(public)',
  {
    ...defaultInfo,
    ...PublicRoute.Route,
  },
)

export const PublicProjektSlug = makeRoute(
  '/(public)/projekt/[slug]',
  {
    ...defaultInfo,
    ...PublicProjektSlugRoute.Route,
  },
)

export const PublicProjektSlugId = makeRoute(
  '/(public)/projekt/[slug]/[id]',
  {
    ...defaultInfo,
    ...PublicProjektSlugIdRoute.Route,
  },
)

export const PublicProjekti = makeRoute(
  '/(public)/projekti',
  {
    ...defaultInfo,
    ...PublicProjektiRoute.Route,
  },
)

export const ApiAuthNextauth = makeRoute(
  '/api/auth/[...nextauth]',
  {
    ...defaultInfo,
    ...ApiAuthNextauthRoute.Route,
  },
)

export const ApiUploadthing = makeRoute(
  '/api/uploadthing',
  {
    ...defaultInfo,
    ...ApiUploadthingRoute.Route,
  },
)

export const AuthError = makeRoute(
  '/auth/error',
  {
    ...defaultInfo,
    ...AuthErrorRoute.Route,
  },
)

export const AuthLogin = makeRoute(
  '/auth/login',
  {
    ...defaultInfo,
    ...AuthLoginRoute.Route,
  },
)

export const AuthNewPassword = makeRoute(
  '/auth/new-password',
  {
    ...defaultInfo,
    ...AuthNewPasswordRoute.Route,
  },
)

export const AuthNewVerification = makeRoute(
  '/auth/new-verification',
  {
    ...defaultInfo,
    ...AuthNewVerificationRoute.Route,
  },
)

export const AuthRegister = makeRoute(
  '/auth/register',
  {
    ...defaultInfo,
    ...AuthRegisterRoute.Route,
  },
)

export const AuthResetPassword = makeRoute(
  '/auth/reset-password',
  {
    ...defaultInfo,
    ...AuthResetPasswordRoute.Route,
  },
)
