import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { SessionProvider } from 'next-auth/react';
import { auth } from '@/auth';
import Navigation from '@/components/containers/navigation';
import { User } from 'next-auth';
import { ThemeProvider } from '@/providers/theme-provider';
import WithLayout from '@/components/with-layout';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
            <WithLayout layout="home">{children}</WithLayout>
          </ThemeProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
