import '../../globals.css'

import type { Metadata } from 'next'
import { Archivo, Montserrat } from 'next/font/google'
import { SessionProvider } from 'next-auth/react'
import React from 'react'

import { getAllLocations } from '@/actions/get-all-locations'
import { auth } from '@/auth'
import { Toaster } from '@/components/ui/toaster'
import WithDashBoardNavigation from '@/components/with-dashboard-navigation'

const montserrat = Montserrat({
  subsets: [ 'latin' ],
})

const archivo = Archivo({
  subsets: [ 'latin' ], variable: '--font-archivo',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()

  const location = (await getAllLocations()) || []

  return (
    <SessionProvider session={session}>
      <html lang='sl'>
        <body className={`${montserrat.className} ${archivo.variable}`}>
          <WithDashBoardNavigation navItems={location}>{children}</WithDashBoardNavigation>
          <Toaster />
        </body>
      </html>
    </SessionProvider>
  )
}
