import '../globals.css'

import type { Metadata } from 'next'
import { Archivo, Montserrat } from 'next/font/google'
import { SessionProvider } from 'next-auth/react'
import React from 'react'
import { Toaster } from 'sonner'

import { auth } from '@/auth'
import WithLayout from '@/components/with-layout'

const montserrat = Montserrat({
  subsets: [ 'latin' ],
})

const archivo = Archivo({
  subsets: [ 'latin' ], variable: '--font-archivo',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()

  return (
    <SessionProvider session={session}>
      <html lang='sl'>
        <body className={`${montserrat.className} ${archivo.variable} overflow-x-hidden bg-body-75`}>
          <WithLayout layout='centered'>{children}</WithLayout>
          <Toaster position="top-center" />
        </body>
      </html>
    </SessionProvider>
  )
}
